"""Import a trusted bundle generated by this project's Colab notebook."""
import argparse
from pathlib import Path
import sys

BASE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BASE))
from restoration.prepare import safe_extract
from relocate_tracking import relocate

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("bundle", type=Path)
    parser.add_argument("--artifacts", type=Path, default=BASE / "artifacts")
    args = parser.parse_args()
    safe_extract(args.bundle, args.artifacts)
    relocate(args.artifacts)
    print("Imported models and records. Restart the application to refresh inference sessions.")
