"""Resumable training + real Optuna studies + MLflow tracking.

Final runs restart from scratch after search; 'last.pt' supports recovery and
'best.pt' is selected only by validation. Official test data is never loaded.
"""
from __future__ import annotations

import argparse
from contextlib import nullcontext
import copy
import json
import os
from pathlib import Path
import random
import time

import mlflow
import numpy as np
import optuna
import torch
from torch import nn
import torch.nn.functional as F

from .data import loaders
from .models import Autoencoder, Classifier, Discriminator, Generator, SoftMixture, build, reconstruction, ssim
from .prepare import write_json, checksum
from .backup import snapshot

TASKS = ("universal", "classifier", "specialists", "soft", "gan")
DEFAULT = dict(base=16, latent=128, dropout=0.1, batch_size=32, lr=0.001,
               weight_decay=0.00001, alpha=0.8, temperature=1.0,
               classification_weight=0.1, balance_weight=0.01,
               embedding=8, discriminator_lr=0.0002, l1_weight=100.0)


def seed_all(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_checkpoint(path, device="cpu"):
    # Files generated by this project only; optimizer/RNG states need full loading.
    return torch.load(path, map_location=device, weights_only=False)


def component_models(artifacts, permit_synthetic=False):
    result = []
    for task in ("classifier", "salt", "blur", "occlusion"):
        checkpoint = load_checkpoint(Path(artifacts) / "checkpoints" / task / "best.pt")
        if checkpoint.get("synthetic", False) and not permit_synthetic:
            raise ValueError("Synthetic smoke-test checkpoints cannot initialize a real run")
        model = build(task, checkpoint["config"])
        model.load_state_dict(checkpoint["model"])
        result.append(model)
    return result


def model_from_checkpoint(checkpoint):
    task, cfg = checkpoint["task"], checkpoint["config"]
    if task == "soft":
        gate = Classifier(**checkpoint["component_configs"]["classifier"])
        experts = [Autoencoder(**checkpoint["component_configs"][name]) for name in ("salt", "blur", "occlusion")]
        model = SoftMixture(gate, experts, cfg["temperature"])
    else:
        model = build(task, cfg)
    model.load_state_dict(checkpoint["model"])
    return model


def atomic_torch_save(value, path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".tmp")
    torch.save(value, temporary)
    temporary.replace(path)


def amp_context(device):
    return torch.autocast("cuda", dtype=torch.float16) if device.type == "cuda" else nullcontext()


def psnr(output, target):
    return -10 * torch.log10((output.float() - target.float()).square().mean((1, 2, 3)).clamp_min(1e-10))


@torch.no_grad()
def validate(model, loader, task, cfg, device, max_batches=0, memory_format=torch.contiguous_format):
    model.eval()
    totals, count = {}, 0
    routing_sum = torch.zeros(4, device=device)
    for batch_index, (image, target, label) in enumerate(loader):
        if max_batches and batch_index >= max_batches:
            break
        image, target, label = image.to(device,memory_format=memory_format), target.to(device,memory_format=memory_format), label.to(device)
        if task == "classifier":
            logits = model(image)
            values = {"objective": F.cross_entropy(logits, label),
                      "accuracy": (logits.argmax(1) == label).float().mean()}
        else:
            if task == "gan":
                output = model(image, label)
            elif task == "soft":
                output, weights, _ = model(image)
                routing_sum += weights.sum(0)
            else:
                output = model(image)
            pixel_error = F.l1_loss(output.float(), target.float())
            structural_similarity = ssim(output, target).mean()
            values = {"objective": .8 * pixel_error + .2 * (1 - structural_similarity),
                      "l1": pixel_error, "ssim": structural_similarity,
                      "psnr": psnr(output, target).mean()}
        size = image.shape[0]
        for name, value in values.items():
            totals[name] = totals.get(name, 0.0) + float(value) * size
        count += size
    if count == 0:
        raise RuntimeError("Validation dataset is empty")
    metrics = {name: value / count for name, value in totals.items()}
    if task == "soft":
        for i, value in enumerate(routing_sum / count):
            metrics[f"weight_{i}"] = float(value)
    return metrics


def train_task(task, cfg, args, output_dir, epochs, trial=None):
    seed_all(42)
    device = torch.device(args.device if args.device != "auto" else "cuda" if torch.cuda.is_available() else "cpu")
    if device.type == "cpu":
        torch.set_num_threads(min(4, os.cpu_count() or 1))
    train_loader, valid_loader = loaders(task, args.data, cfg["batch_size"], args.workers)
    components = component_models(args.artifacts, getattr(args, "synthetic", False)) if task == "soft" else None
    model = build(task, cfg, components).to(device)
    memory_format = torch.channels_last if device.type == 'cpu' and getattr(args,'cpu_channels_last',False) else torch.contiguous_format
    model.to(memory_format=memory_format)
    component_configs = {}
    if task == "soft":
        component_configs = {name: load_checkpoint(args.artifacts / "checkpoints" / name / "best.pt")["config"]
                             for name in ("classifier", "salt", "blur", "occlusion")}
    discriminator = Discriminator(**cfg).to(device) if task == "gan" else None
    if discriminator:
        discriminator.to(memory_format=memory_format)
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg["lr"], weight_decay=cfg["weight_decay"],
                                 betas=(0.5, 0.999) if task == "gan" else (0.9, 0.999))
    d_optimizer = torch.optim.Adam(discriminator.parameters(), lr=cfg["discriminator_lr"], betas=(0.5, 0.999)) if discriminator else None
    scaler = torch.amp.GradScaler("cuda", enabled=device.type == "cuda")
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    start_epoch, best, history = 0, float("inf"), []
    fingerprint = checksum(args.data / "manifests" / ("fs2k.json" if task == "gan" else "pets.json"))
    validation_fingerprint = checksum(args.data / "manifests" / ("fs2k.json" if task == "gan" else "pets_validation.json"))
    last = output_dir / "last.pt"
    if last.exists() and trial is None:
        saved = load_checkpoint(last, device)
        if saved["config"] != cfg or saved["manifest_sha256"] != fingerprint or saved["validation_sha256"] != validation_fingerprint:
            raise ValueError("Resume configuration/data changed; use a different artifacts directory")
        model.load_state_dict(saved["model"])
        optimizer.load_state_dict(saved["optimizer"])
        scaler.load_state_dict(saved["scaler"])
        if discriminator:
            discriminator.load_state_dict(saved["discriminator"])
            d_optimizer.load_state_dict(saved["d_optimizer"])
        start_epoch, best, history = saved["epoch"] + 1, saved["best"], saved["history"]
        random.setstate(saved["python_rng"])
        np.random.set_state(saved["numpy_rng"])
        torch.set_rng_state(saved["torch_rng"].cpu())
        if device.type == "cuda" and saved.get("cuda_rng"):
            torch.cuda.set_rng_state_all([s.cpu() for s in saved["cuda_rng"]])
        if hasattr(train_loader.batch_sampler, "epoch"):
            train_loader.batch_sampler.epoch = start_epoch
    tracking_uri = "sqlite:///" + (args.artifacts.resolve() / "tracking.db").as_posix()
    mlflow.set_tracking_uri(tracking_uri)
    experiment_name = "generative-ai-assignment"
    experiment = mlflow.get_experiment_by_name(experiment_name)
    if experiment is None:
        mlflow.create_experiment(experiment_name, artifact_location=(args.artifacts.resolve() / "mlflow_artifacts").as_uri())
    mlflow.set_experiment(experiment_name)
    with mlflow.start_run(run_name=f"{task}-" + (f"trial-{trial.number}" if trial else "final")):
        mlflow.log_params({**cfg, "task": task, "epochs_requested": epochs, "device": str(device),
                           "data_loader_workers": args.workers,
                           "memory_format": 'channels_last' if memory_format == torch.channels_last else 'contiguous',
                           "manifest_sha256": fingerprint, "validation_sha256": validation_fingerprint,
                           "max_train_batches": args.max_train_batches,
                           "max_validation_batches": args.max_validation_batches,
                           "warmup_epochs": args.warmup_epochs if task == "soft" else 0})
        for epoch in range(start_epoch, epochs):
            started = time.time()
            model.train()
            if task == "soft":
                for expert in model.experts:
                    expert.requires_grad_(epoch >= args.warmup_epochs)
                    if epoch < args.warmup_epochs:
                        expert.eval()
            if discriminator:
                discriminator.train()
            totals, count = {}, 0
            for batch_index, (image, target, label) in enumerate(train_loader):
                if args.max_train_batches and batch_index >= args.max_train_batches:
                    break
                image, target, label = image.to(device,memory_format=memory_format), target.to(device,memory_format=memory_format), label.to(device)
                optimizer.zero_grad(set_to_none=True)
                values = {}
                with amp_context(device):
                    if task == "classifier":
                        loss = F.cross_entropy(model(image), label)
                    elif task == "gan":
                        output = model(image, label)
                        discriminator.requires_grad_(True)
                        d_optimizer.zero_grad(set_to_none=True)
                        real = discriminator(image, target, label)
                        fake = discriminator(image, output.detach(), label)
                        real_loss = F.binary_cross_entropy_with_logits(real, torch.ones_like(real))
                        fake_loss = F.binary_cross_entropy_with_logits(fake, torch.zeros_like(fake))
                        d_loss = (real_loss + fake_loss) * 0.5
                        scaler.scale(d_loss).backward()
                        scaler.step(d_optimizer)
                        discriminator.requires_grad_(False)
                        generated = discriminator(image, output, label)
                        adversarial = F.binary_cross_entropy_with_logits(generated, torch.ones_like(generated))
                        pixel_loss = F.l1_loss(output, target)
                        loss = adversarial + cfg["l1_weight"] * pixel_loss
                        values.update(discriminator_real=float(real_loss.detach()), discriminator_fake=float(fake_loss.detach()),
                                      generator_adversarial=float(adversarial.detach()), generator_reconstruction=float(pixel_loss.detach()))
                    elif task == "soft":
                        output, weights, logits = model(image)
                        pixel_loss = F.l1_loss(output.float(), target.float())
                        structural = 1 - ssim(output, target).mean()
                        classification = F.cross_entropy(logits, label)
                        balance = (weights.mean(0) - 0.25).square().sum()
                        loss = cfg["alpha"] * pixel_loss + (1 - cfg["alpha"]) * structural + cfg["classification_weight"] * classification + cfg["balance_weight"] * balance
                        values.update(reconstruction=float(pixel_loss.detach()), structural=float(structural.detach()),
                                      classification=float(classification.detach()), balance=float(balance.detach()))
                    else:
                        loss = reconstruction(model(image), target, cfg["alpha"])
                if not torch.isfinite(loss):
                    raise RuntimeError(f"Non-finite training loss in {task}")
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                nn.utils.clip_grad_norm_(model.parameters(), 5.0)
                scaler.step(optimizer)
                scaler.update()
                values["loss"] = float(loss.detach())
                count += image.shape[0]
                for name, value in values.items():
                    totals[name] = totals.get(name, 0.0) + value * image.shape[0]
            if count == 0:
                raise RuntimeError("Training dataset produced no batches")
            validation = validate(model, valid_loader, task, cfg, device, args.max_validation_batches, memory_format)
            metrics = {"train_" + name: value / count for name, value in totals.items()}
            metrics.update({"validation_" + name: value for name, value in validation.items()})
            metrics.update(seconds=time.time() - started, epoch=epoch + 1)
            improved = validation["objective"] < best
            best = min(best, validation["objective"])
            history.append(metrics)
            saved = {"task": task, "config": cfg, "model": model.state_dict(), "optimizer": optimizer.state_dict(),
                     "scaler": scaler.state_dict(), "epoch": epoch, "best": best, "history": history,
                     "manifest_sha256": fingerprint, "validation_sha256": validation_fingerprint,
                     "execution_memory_format": 'channels_last' if memory_format == torch.channels_last else 'contiguous',
                     "component_configs": component_configs,
                     "synthetic": bool(getattr(args, "synthetic", False)), "python_rng": random.getstate(), "numpy_rng": np.random.get_state(),
                     "torch_rng": torch.get_rng_state(),
                     "cuda_rng": torch.cuda.get_rng_state_all() if device.type == "cuda" else None}
            if discriminator:
                saved.update(discriminator=discriminator.state_dict(), d_optimizer=d_optimizer.state_dict())
            atomic_torch_save(saved, last)
            if improved:
                atomic_torch_save(saved, output_dir / "best.pt")
            write_json(output_dir / "history.json", history)
            mlflow.log_metrics(metrics, step=epoch)
            if task != "classifier" and (epoch == 0 or (epoch + 1) % 5 == 0 or epoch == epochs - 1):
                log_examples(model, valid_loader, task, device, epoch, output_dir)
            print(json.dumps({"task": task, **metrics}), flush=True)
            if getattr(args, "backup", None) and trial is None and "checkpoints" in output_dir.parts:
                snapshot(args.artifacts, args.backup, task)
            if trial is not None:
                trial.report(validation["objective"], epoch)
                if trial.should_prune():
                    raise optuna.TrialPruned()
        mlflow.log_artifact(str(output_dir / "history.json"))
    return best


@torch.no_grad()
def log_examples(model, loader, task, device, epoch, output_dir):
    from PIL import Image
    model.eval()
    image, target, label = next(iter(loader))
    image, target, label = image[:4].to(device), target[:4].to(device), label[:4].to(device)
    output = model(image, label) if task == "gan" else model(image)
    if task == "soft":
        output = output[0]
    canvas = Image.new("RGB", (128 * 4, 128 * len(image)))
    for i in range(len(image)):
        error = (output[i] - target[i]).abs()
        for column, value in enumerate((image[i], target[i], output[i], error)):
            array = (value.detach().cpu().permute(1, 2, 0).numpy().clip(0, 1) * 255).astype(np.uint8)
            canvas.paste(Image.fromarray(array), (column * 128, i * 128))
    path = output_dir / f"validation-epoch-{epoch + 1:03}.png"
    canvas.save(path)
    mlflow.log_artifact(str(path), artifact_path="validation_samples")


def search_config(trial, task, spatial=False, detail=False, gan_refined=False):
    cfg = dict(DEFAULT)
    cfg["batch_size"] = trial.suggest_categorical("batch_size", [16, 32, 64])
    cfg["lr"] = trial.suggest_float("lr", 1e-5 if task == "soft" else 1e-4,
                                  3e-4 if task == "soft" else 5e-4 if detail or gan_refined else 3e-3, log=True)
    if task != "soft":
        cfg["base"] = trial.suggest_categorical("base", [16, 24, 32] if detail or gan_refined else [8, 16, 24])
        cfg["dropout"] = trial.suggest_float("dropout", 0.0, 0.08 if detail or gan_refined else 0.3)
    if task in ("universal", "specialists"):
        cfg["latent"] = trial.suggest_categorical("latent", [2048, 4096, 8192] if detail else [256, 512, 1024] if spatial else [64, 128, 256])
        cfg["alpha"] = trial.suggest_float("alpha", 0.6, 0.95)
    elif task == "classifier":
        cfg["weight_decay"] = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
    elif task == "soft":
        cfg["temperature"] = trial.suggest_float("temperature", 0.5, 2.0)
        cfg["classification_weight"] = trial.suggest_float("classification_weight", 0.02, 0.3, log=True)
        cfg["balance_weight"] = trial.suggest_float("balance_weight", 0.001, 0.1, log=True)
        cfg["alpha"] = trial.suggest_float("alpha", 0.6, 0.95)
    elif task == "gan":
        cfg["discriminator_lr"] = trial.suggest_float("discriminator_lr", 1e-4, 1e-3, log=True)
        cfg["embedding"] = trial.suggest_categorical("embedding", [4, 8, 16])
        cfg["l1_weight"] = trial.suggest_float("l1_weight", 50, 150)
    return cfg


def tune(task, args):
    args.artifacts.mkdir(parents=True, exist_ok=True)
    storage = "sqlite:///" + (args.artifacts.resolve() / "optuna.db").as_posix()
    study = optuna.create_study(study_name=task, storage=storage, load_if_exists=True, direction="minimize",
                                sampler=optuna.samplers.TPESampler(seed=42),
                                pruner=optuna.pruners.MedianPruner(n_startup_trials=2, n_warmup_steps=1))
    if task in ("universal", "specialists") and any(
        (bool(t.user_attrs.get("full_config", {}).get("normalized", False)) != args.normalized or
         bool(t.user_attrs.get("full_config", {}).get("spatial", False)) != args.spatial or
         bool(t.user_attrs.get("full_config", {}).get("detail", False)) != args.detail or
         bool(t.user_attrs.get("full_config", {}).get("detail_bn", False)) != args.detail_bn or
         bool(t.user_attrs.get("full_config", {}).get("detail_shuffle", False)) != args.detail_shuffle)
        for t in study.trials if "full_config" in t.user_attrs
    ):
        raise ValueError("Architecture changed: use a separate artifacts directory for the repair study")
    trial_args = copy.copy(args)
    trial_args.max_train_batches = args.trial_train_batches
    trial_args.max_validation_batches = args.trial_validation_batches
    def objective(trial):
        cfg = search_config(trial, task, args.spatial, args.detail, args.gan_refined)
        if args.detail and task in ("universal", "specialists"):
            cfg["detail"] = True
            cfg["detail_bn"] = args.detail_bn
            cfg["detail_shuffle"] = args.detail_shuffle
        if args.gan_refined and task == "gan":
            cfg["gan_refined"] = True
        if args.normalized and task in ("universal", "specialists"):
            cfg["normalized"] = True
        if args.spatial and task in ("universal", "specialists"):
            cfg["spatial"] = True
        trial.set_user_attr("full_config", cfg)
        directory = args.artifacts / "trials" / task / str(trial.number)
        if task == "specialists":
            # Common architecture scored across ALL THREE corruption specialists.
            values = [train_task(kind, cfg, trial_args, directory / kind, args.trial_epochs)
                      for kind in ("salt", "blur", "occlusion")]
            return float(np.mean(values))
        return train_task(task, cfg, trial_args, directory, args.trial_epochs, trial)
    finished = sum(t.state in (optuna.trial.TrialState.COMPLETE, optuna.trial.TrialState.PRUNED) for t in study.trials)
    study.optimize(objective, n_trials=max(0, args.trials - finished))
    complete = [t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE]
    if not complete:
        raise RuntimeError(f"No completed trial for {task}")
    cfg = study.best_trial.user_attrs["full_config"]
    write_json(args.artifacts / "configs" / f"{task}.json", cfg)
    write_json(args.artifacts / "studies" / f"{task}.json", {
        "task": task, "best_trial": study.best_trial.number, "best_value": study.best_value,
        "completed": len(complete), "pruned": sum(t.state == optuna.trial.TrialState.PRUNED for t in study.trials),
        "budget": {"epochs": args.trial_epochs, "train_batches": args.trial_train_batches,
                   "validation_batches": args.trial_validation_batches},
        "search_space": {name: str(distribution) for name, distribution in study.best_trial.distributions.items()},
        "trials": [{"number": t.number, "state": t.state.name, "value": t.value, "params": t.params} for t in study.trials]})
    if getattr(args, "backup", None):
        snapshot(args.artifacts, args.backup)
    return cfg


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", choices=TASKS, required=True)
    parser.add_argument("--mode", choices=("tune", "train", "both"), default="both")
    parser.add_argument("--data", type=Path, default=Path("data"))
    parser.add_argument("--artifacts", type=Path, default=Path("artifacts"))
    parser.add_argument("--config", type=Path)
    parser.add_argument("--normalized", action="store_true",
                        help="Use GroupNorm/LeakyReLU autoencoders in a fresh tuning study")
    parser.add_argument("--spatial", action="store_true",
                        help="Use a compressed spatial latent and resize-convolution decoder")
    parser.add_argument("--detail", action="store_true",
                        help="Use a 16x16 compressed latent and local residual refinement without bypasses")
    parser.add_argument("--detail-bn", action="store_true",
                        help="Use batch normalization with tracked inference statistics in detail models")
    parser.add_argument("--detail-shuffle", action="store_true",
                        help="Learn sub-pixel upsampling filters in the detail decoder")
    parser.add_argument("--gan-refined", action="store_true",
                        help="Use normalized U-Net/PatchGAN with learned sub-pixel decoder stages")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--trials", type=int, default=4)
    parser.add_argument("--trial-epochs", type=int, default=3)
    parser.add_argument("--trial-train-batches", type=int, default=40)
    parser.add_argument("--trial-validation-batches", type=int, default=20)
    parser.add_argument("--max-train-batches", type=int, default=0)
    parser.add_argument("--max-validation-batches", type=int, default=0)
    parser.add_argument("--warmup-epochs", type=int, default=2)
    parser.add_argument("--workers", type=int, default=0)
    parser.add_argument("--device", default="auto")
    parser.add_argument('--cpu-channels-last',action='store_true',
                        help='Use a benchmarked CPU tensor layout; model shapes and losses remain unchanged')
    parser.add_argument("--backup", type=Path, help="Persistent backup directory; SQLite runs on local disk")
    args = parser.parse_args()
    args.artifacts.mkdir(parents=True, exist_ok=True)
    cfg_path = args.config or args.artifacts / "configs" / f"{args.task}.json"
    if args.mode in ("tune", "both"):
        cfg = tune(args.task, args)
    elif cfg_path.exists():
        cfg = {**DEFAULT, **json.loads(cfg_path.read_text())}
    else:
        raise FileNotFoundError(f"Run tuning first or provide --config: {cfg_path}")
    if args.mode in ("train", "both"):
        targets = ("salt", "blur", "occlusion") if args.task == "specialists" else (args.task,)
        for task in targets:
            train_task(task, cfg, args, args.artifacts / "checkpoints" / task, args.epochs)


if __name__ == "__main__":
    main()
